basePath: /
host: localhost:3000
info:
  contact: {}
  description: Go-Cloak, Echo, Swagger
  title: Echo Swagger Go-Cloak
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /login:
    post:
      consumes:
      - multipart/form-data
      description: Login Go-Cloak.
      parameters:
      - description: Username
        in: formData
        name: user
        required: true
        type: string
      - description: Password
        in: formData
        name: pass
        required: true
        type: string
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Login Go-Cloak.
      tags:
      - root
schemes:
- http
swagger: "2.0"
