version: "3"

services:
  go:
    image: golang:latest
    volumes:
      - ./src:/src
      - ./go-build:/root/.cache/go-build
      - ./go-mod:/go/pkg/mod
    ports:
      - 3000:3000
    working_dir: /src
    command: sh -c "go run main.go"
    # restart: always

  postgres:
    image: postgres:10
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HOSTNAME: localhost
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
      #--trust-proxy-verification --hostname-strict=false start-dev
    command: start-dev
    ports:
      - 8080:8080

volumes:
  golang-test:
    external: true
